version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1
  cloudrun: circleci/gcp-cloud-run@1.0.0
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm && npm install yarn"
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Build React App
          command: yarn build
      - save_cache:
          key: app-build-cache-{{ .Branch }}
          paths:
            - ./dist
      - gcp-gcr/gcr-auth:
          gcloud-service-key: GOOGLE_CLOUD_KEYS
          google-project-id: GOOGLE_PROJECT_ID
          google-compute-zone: GOOGLE_COMPUTE_ZONE
      - gcp-gcr/push-image:
          google-project-id: GOOGLE_PROJECT_ID
          registry-url: "gcr.io"
          image: $IMAGE_NAME
      - cloudrun/deploy:
          platform: "managed"
          image: "gcr.io/hackatum2020/cra-cloud-run"
          service-name: "orb-gcp-cloud-run"
          region: europe-central2-a
          unauthenticated: true
      - run:
          name: Deploy to Google Cloud
          command: gcloud builds submit --tag gcr.io/hackatum2020/cra-cloud-run
workflows:
  version: 2
  build-and-deploy-gc-workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
